name: Auto Generate Sidebar

on:
  push:
    paths:
      - "**/*.md"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate sidebar
        run: |
          bash generate_sidebar.sh

      - name: Commit sidebar
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _sidebar.md
          git commit -m "auto: update sidebar" || echo "no change"
          git push
